(torch_pyl) pyl@ubuntu-server:~/codes$ sudo conda install pytorch torchvision torchaudio pytorch-cuda=12.2 -c pytorch -c nvidia

Channels:
 - pytorch
 - nvidia
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/exception_handler.py", line 28, in __call__
        return func(*args, **kwargs)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/cli/main.py", line 61, in main_subshell
        exit_code = do_call(args, parser)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/cli/conda_argparse.py", line 206, in do_call
        result = getattr(module, func_name)(args, parser)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/notices/core.py", line 141, in wrapper
        return func(*args, **kwargs)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/cli/main_install.py", line 165, in execute
        install(args, parser, "install")
        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/cli/install.py", line 439, in install
        unlink_link_transaction = solver.solve_for_transaction(
            deps_modifier=deps_modifier,
        ...<4 lines>...
            ),
        )
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ~~~~~~~~~~~~~~~~~~~^
            update_modifier,
            ^^^^^^^^^^^^^^^^
        ...<5 lines>...
            should_retry_solve,
            ^^^^^^^^^^^^^^^^^^^
        )
        ^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/core/solve.py", line 225, in solve_for_diff
        final_precs = self.solve_final_state(
            update_modifier,
        ...<4 lines>...
            should_retry_solve,
        )
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/solver.py", line 166, in solve_final_state
        index = self._collect_all_metadata(
            channels=channels,
        ...<2 lines>...
            in_state=in_state,
        )
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/common/io.py", line 87, in decorated
        return f(*args, **kwds)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/solver.py", line 265, in _collect_all_metadata
        index = LibMambaIndexHelper(
            channels=[*conda_build_channels, *channels],
        ...<6 lines>...
            pkgs_dirs=context.pkgs_dirs if context.offline else (),
        )
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/index.py", line 181, in __init__
        self.repos: list[_ChannelRepoInfo] = self._load_channels()
                                             ~~~~~~~~~~~~~~~~~~~^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/index.py", line 285, in _load_channels
        urls_to_json_path_and_state = self._fetch_repodata_jsons(tuple(urls_to_channel.keys()))
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/index.py", line 349, in _fetch_repodata_jsons
        for (url, path, state) in executor.map(self._fetch_one_repodata_json, urls)
                                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/work_home/root/yes/lib/python3.13/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ~~~~~~~~~~~~~~~~~^^^^^^^^^^
      File "/work_home/root/yes/lib/python3.13/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ~~~~~~~~~~^^^^^^^^^
      File "/work_home/root/yes/lib/python3.13/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ~~~~~~~~~~~~~~~~~^^
      File "/work_home/root/yes/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/work_home/root/yes/lib/python3.13/concurrent/futures/thread.py", line 59, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda_libmamba_solver/index.py", line 375, in _fetch_one_repodata_json
        json_path, state = subdir_data.repo_fetch.fetch_latest_path()
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/gateways/repodata/__init__.py", line 749, in fetch_latest_path
        _, state = self.fetch_latest()
                   ~~~~~~~~~~~~~~~~~^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/gateways/repodata/__init__.py", line 789, in fetch_latest
        cache.load_state()
        ~~~~~~~~~~~~~~~~^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/gateways/repodata/__init__.py", line 585, in load_state
        self.load(state_only=True)
        ~~~~~~~~~^^^^^^^^^^^^^^^^^
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/gateways/repodata/__init__.py", line 532, in load
        with self.lock("r+") as state_file:
             ~~~~~~~~~^^^^^^
      File "/work_home/root/yes/lib/python3.13/contextlib.py", line 141, in __enter__
        return next(self.gen)
      File "/work_home/root/yes/lib/python3.13/site-packages/conda/gateways/repodata/__init__.py", line 651, in lock
        with self.cache_path_state.open(mode) as state_file, lock(state_file):
             ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
      File "/work_home/root/yes/lib/python3.13/pathlib/_local.py", line 537, in open
        return io.open(self, mode, buffering, encoding, errors, newline)
               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 13] Permission denied: '/work_home/root/yes/pkgs/cache/9dbdbf81.info.json'

`$ /work_home/root/yes/bin/conda install pytorch torchvision torchaudio pytorch-cuda=12.2 -c pytorch -c nvidia`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/work_home/root/yes/envs/torch_pyl:/work_home/root/yes/envs/torch_pyl/
                          x86_64-conda-linux-gnu/sysroot/usr
      CONDA_BUILD_SYSROOT=/work_home/root/yes/envs/torch_pyl/x86_64-conda-linux-gnu/sysroot
        CONDA_DEFAULT_ENV=torch_pyl
                CONDA_EXE=/work_home/root/yes/bin/conda
             CONDA_PREFIX=/work_home/root/yes/envs/torch_pyl
           CONDA_PREFIX_1=/work_home/root/yes
    CONDA_PROMPT_MODIFIER=(torch_pyl)
         CONDA_PYTHON_EXE=/work_home/root/yes/bin/python
               CONDA_ROOT=/work_home/root/yes
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/work_home/root/yes/envs/torch_pyl/bin:/work_home/root/yes/condabin:/w
                          ork_home/root/yes/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : torch_pyl
    active env location : /work_home/root/yes/envs/torch_pyl
            shell level : 2
       user config file : /work_home/pyl/.condarc
 populated config files : /work_home/root/yes/.condarc
          conda version : 25.7.0
    conda-build version : not installed
         python version : 3.13.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=25.7.0=0
                          __cuda=12.2=0
                          __glibc=2.31=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /work_home/root/yes  (writable)
      conda av data dir : /work_home/root/yes/etc/conda
  conda av metadata url : None
           channel URLs : http://10.155.97.247:8088/repository/conda-extra-proxy/pytorch/linux-64
                          http://10.155.97.247:8088/repository/conda-extra-proxy/pytorch/noarch
                          http://10.155.97.247:8088/repository/conda-proxy/nvidia/linux-64
                          http://10.155.97.247:8088/repository/conda-proxy/nvidia/noarch
                          http://10.155.97.247:8088/repository/conda-proxy/main/linux-64
                          http://10.155.97.247:8088/repository/conda-proxy/main/noarch
                          http://10.155.97.247:8088/repository/conda-proxy/free/linux-64
                          http://10.155.97.247:8088/repository/conda-proxy/free/noarch
                          http://10.155.97.247:8088/repository/conda-proxy/r/linux-64
                          http://10.155.97.247:8088/repository/conda-proxy/r/noarch
          package cache : /work_home/root/yes/pkgs
                          /work_home/pyl/.conda/pkgs
       envs directories : /work_home/root/yes/envs
                          /work_home/pyl/.conda/envs
               platform : linux-64
             user-agent : conda/25.7.0 requests/2.32.4 CPython/3.13.5 Linux/5.4.0-26-generic ubuntu/20.04 glibc/2.31 solver/libmamba conda-libmamba-solver/25.4.0 libmambapy/2.0.5 aau/0.7.1 c/. s/. e/.
                UID:GID : 1010:1010
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
